title: "RABMEN SECURITY HUB"
description: "RABMEN SECURITY HUB"
url: "https://ariyts.github.io"
baseurl: ""

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# Автор
author:
  name: "RABMEN"
  avatar: "/assets/images/avatar.png"
  bio: "Security researcher & pentester notes"
  location: "Cyberspace"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Ariyts"
    - label: "Telegram"
      icon: "fab fa-telegram"
      url: "https://t.me/yourchannel"

# Навигация (верхнее меню)
nav:
  - title: "Главная"
    url: /
  - title: "Заметки"
    url: /notes/
  - title: "Обо мне"
    url: /about/

# Коллекции (для заметок)
collections:
  notes:
    output: true
    permalink: /:collection/:name

# Плагины
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Настройки отображения по умолчанию (ЕДИНЫЙ БЛОК)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_sticky: true

  - scope:
      path: ""
      type: "notes"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "notes_sidebar"
      toc: true
      toc_sticky: true

# Описание бокового меню для заметок
notes_sidebar:
  - title: "Nmap"
    children:
      - title: "Обнаружение хостов"
        url: /notes/nmap-01-host-discovery/
      - title: "Сканирование портов"
        url: /notes/nmap-02-port-scanning-basics/
      - title: "Работа с DNS"
        url: /notes/nmap-03-dns-tricks/
  - title: "Другие инструменты"
    children:
      - title: "Скоро..."
        url: "#"
  - title: "Burp Suite"  # <-- НОВАЯ КАТЕГОРИЯ
    children:
      - title: "Введение и настройка" # <-- НОВАЯ ССЫЛКА
        url: /notes/burp_Suite_pro/ # <-- ПУТЬ = /notes/ + ИМЯ_ФАЙЛА (без .md)