title: "RABMEN SECURITY HUB"
description: "RABMEN SECURITY HUB"
url: "https://ariyts.github.io"   # адрес сайта
baseurl: ""                       # если сайт в корне (ariyts.github.io), оставь пустым

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"     # варианты: default, dark, dirt, neon, air, sunrise, contrast, mint, plum

# Автор
author:
  name: "RABMEN"
  avatar: "/assets/images/avatar.png"   # добавь картинку в assets/images
  bio: "Security researcher & pentester notes"
  location: "Cyberspace"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Ariyts"
    - label: "Telegram"
      icon: "fab fa-telegram"
      url: "https://t.me/yourchannel"

# Навигация (верхнее меню)
nav:
  - title: "Главная"
    url: /
  - title: "Заметки"
    url: /notes/
  - title: "Обо мне"
    url: /about/

# Коллекции (для заметок)
collections:
  notes:
    output: true
    permalink: /:collection/:name

# Плагины
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Настройки отображения по умолчанию
# Настройки отображения по умолчанию (ОБЪЕДИНЕННАЯ ВЕРСИЯ)
defaults:
  # Настройки для постов (если они у вас будут)
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_sticky: true

  # Настройки для наших заметок (notes)
  - scope:
      path: ""
      type: "notes"
    values:
      layout: single
      author_profile: true # Показываем профиль автора в заметках
      sidebar:
        nav: "notes_sidebar" # Включаем боковую навигацию
      toc: true
      toc_sticky: true


# Боковая навигация для раздела "Заметки"
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: single
      author_profile: true # Показываем профиль автора в заметках
      sidebar:
        nav: "notes_sidebar"
      toc: true
      toc_sticky: true
# (у вас уже есть блок defaults, добавьте это в него или объедините)

# Описание самого меню
notes_sidebar:
  - title: "Nmap"
    children:
      - title: "Обнаружение хостов"
        url: /notes/nmap-01-host-discovery/
      - title: "Сканирование портов"
        url: /notes/nmap-02-port-scanning-basics/
      - title: "Работа с DNS"
        url: /notes/nmap-03-dns-tricks/
  - title: "Другие инструменты"
    children:
      - title: "Скоро..."
        url: "#"